name: check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install .  # Install current repository
        pip install -e .[dev]  # Install current repository in dev mode

    - name: Checkout inseeds repository
      run: |
        git clone https://github.com/pik-copan/inseeds.git
        cd inseeds
        pip install -e .  # Install inseeds in editable mode

    - name: Run tests for pycopanlpjml
      run: |
        pytest --cov --cov-report=xml

    - name: Run tests for inseeds
      run: |
        cd inseeds
        pytest

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Lint code with Flake8
      run: |
        flake8 .
